import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Provider from "@/lib/provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Provider>
        <body
          className={`max-w-lg m-auto p-3 dark:bg-black dark:text-white ${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <div className="">
            <div className="p-2 border border-gray-500  rounded">
              {children}
            </div>
          </div>
        </body>
      </Provider>
    </html>
  );
}
